name: shedmate
description: "Jazz practice tools for musicians"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_midi_pro:
    git:
      url: https://github.com/brenzi/flutter_midi_pro.git
      ref: ab/expose-realtime-note-injection
  shared_preferences: ^2.5.4
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sf2/
